name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: install depedendices
      run : |
        cd simple-packaging
        python -m pip install --upgrade pip
        pip install .
        pip install sphinx myst-parser
    - name: Build HTML
      run: |
        cd simple-packaging/docs
        make html
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: simple-packaging/docs/build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: simple-packaging/docs/build/html